# Generated by Django 4.2.1 on 2023-05-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_service', '0002_rename_name_user_username_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
